### ISSUE TITLE
About running the app

### ISSUE THREAD

**Issue by PengW9996** [miguellopezbecona/Tweet-Getter#1]
Hi, there are some errors(such as syntax errors and type errors) when I tried to run the app

**Comment by miguellopezbecona** [comment]
I checked the code and it seems the issue was that it was written using Python2, which is deprecated nowadays (note that this project was made several years ago). I adapted it to Python3, so it should work now (I already tested it). Remember to fill the blanks within "initializeAPI" function with your private keys.
Thank you for your feedback.
